<a href="https://colab.research.google.com/github/giolanta-nta/Homework/blob/main/Data_centers_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv("/combined_data.csv")
df

,Continent,Regions,Code,Zones,City,State,Country,Opened,Latitude,Longitude,Company,Location
0,Asia,China,cn-qingdao,2,Qingdao,NaN,China,2012,36.11670,120.4000,alibaba,"Qingdao, China"
1,Asia,China,cn-beijing,12,Beijing,NaN,China,2013,39.90400,116.4075,alibaba,"Beijing, China"
2,Asia,China,cn-zhangjiakou,3,Zhangjiakou,NaN,China,2014,40.81080,114.8811,alibaba,"Zhangjiakou, China"
3,Asia,China,cn-huhehaote,2,Hohhot,NaN,China,2017,40.81510,111.6629,alibaba,"Hohhot, China"
4,Asia,China,cn-wulanchabu,3,Ulanqab,NaN,China,2020,40.99490,113.1320,alibaba,"Ulanqab, China"
...,...,...,...,...,...,...,...,...,...,...,...,...
225,Asia,UAE East,me-dubai-1,1,Dubai,NaN,UAE,2020,25.20480,55.2708,oracle,"Dubai, UAE"
226,Asia,UAE Central,me-abudhabi-1,1,Abu Dhabi,NaN,UAE,2021,24.45390,54.3773,oracle,"Abu Dhabi, UAE"
227,Asia,Israel 2,TBD,1,Tel Aviv,NaN,Israel,Future,32.08530,34.7818,oracle,"Tel Aviv, Israel"
228,Asia,Saudi Arabia 2,TBD,1,Riyadh,NaN,Saudi Arabia,Future,24.63330,46.7167,oracle,"Riyadh, Saudi Arabia"
229,Asia,Saudi Arabia 3,TBD,1,Neom,NaN,Saudi Arabia,Future,28.00639,35.2025,oracle,"Neom, Saudi Arabia"

In [4]:
df.dtypes

Continent     object
Regions       object
Code          object
Zones          int64
City          object
State         object
Country       object
Opened        object
Latitude     float64
Longitude    float64
Company       object
Location      object
dtype: object

In [5]:
df.shape

(230, 12)

In [6]:
df.sort_values(by="Latitude")

,Continent,Regions,Code,Zones,City,State,Country,Opened,Latitude,Longitude,Company,Location
52,Oceania,Asia Pacific,ap-southeast-4,3,Melbourne,NaN,Australia,2023,-37.8142,144.9631,amazon,"Melbourne, Australia"
105,Oceania,Melbourne,australia-southeast2,3,Melbourne,NaN,Australia,2021,-37.8142,144.9631,google,"Melbourne, Australia"
212,Oceania,Australia Southeast,ap-melbourne-1,1,Melbourne,NaN,Australia,2020,-37.8142,144.9631,oracle,"Melbourne, Australia"
106,Oceania,New Zealand,TBD,3,Auckland,NaN,New Zealand,Future,-36.8406,174.7400,google,"Auckland, New Zealand"
46,Oceania,Asia Pacific,ap-southeast-5,3,Auckland,NaN,New Zealand,2024,-36.8406,174.7400,amazon,"Auckland, New Zealand"
...,...,...,...,...,...,...,...,...,...,...,...,...
168,Europe,Norway East,norwayeast,3,Oslo,NaN,Norway,2019,59.9133,10.7389,microsoft,"Oslo, Norway"
157,Europe,Finland Central,finlandcentral,1,Helsinki,NaN,Finland,Future,60.1708,24.9375,microsoft,"Helsinki, Finland"
80,Europe,Finland,europe-north1,3,Hamina,NaN,Finland,2018,60.5667,27.2000,google,"Hamina, Finland"
173,Europe,Sweden Central,swedencentral,3,Gavle,NaN,Sweden,2021,60.6747,17.1417,microsoft,"Gavle, Sweden"
116,Europe,NaN,NaN,1,Lulea,NaN,Sweden,2013,65.5848,22.1567,meta,"Lulea, Sweden"

In [9]:
df.value_counts()

Continent      Regions              Code                     Zones  City            State           Country        Opened  Latitude  Longitude  Company    Location
North America  AWS GovCloud         us-gov-east-1            3      Columbus        Ohio            United States  2018     32.5100  -84.8771   amazon     Columbus, Ohio, United States                   1
               Canada               ca-central-1             3      Montreal        Quebec          Canada         2016     45.5089  -73.5617   amazon     Montreal, Quebec, Canada                        1
                                    ca-west-1                3      Calgary         Alberta         Canada         2024     51.0500  -114.0667  amazon     Calgary, Alberta, Canada                        1
               Canada Central       canadacentral            3      Toronto         Ontario         Canada         2016     43.7417  -79.3733   microsoft  Toronto, Ontario, Canada                        1
               Canada East          canadaeast               1      Quebec City     Quebec          Canada         2016     46.8139  -71.2081   microsoft  Quebec City, Quebec, Canada                     1
               Canada Southeast     ca-montreal-1            1      Montreal        Quebec          Canada         2020     45.5089  -73.5617   oracle     Montreal, Quebec, Canada                        1
                                    ca-toronto-1             1      Toronto         Ontario         Canada         2019     43.7417  -79.3733   oracle     Toronto, Ontario, Canada                        1
               Central US           centralus                3      Des Moines      Iowa            United States  2014     41.5725  -93.6105   microsoft  Des Moines, Iowa, United States                 1
               Columbus             us-east5                 3      Columbus        Ohio            United States  2022     39.9862  -82.9855   google     Columbus, Ohio, United States                   1
               Dallas               us-south1                3      Dallas          Texas           United States  2022     32.7935  -96.7667   google     Dallas, Texas, United States                    1
               East US              eastus                   3      Richmond        Virginia        United States  2012     37.5295  -77.4756   microsoft  Richmond, Virginia, United States               1
               East US 3            eastus3                  3      Atlanta         Georgia         United States  Future   33.7628  -84.4220   microsoft  Atlanta, Georgia, United States                 1
               Iowa                 us-central1              4      Council Bluffs  Iowa            United States  2013     41.2369  -95.8516   google     Council Bluffs, Iowa, United States             1
               Las Vegas            us-west4                 3      Las Vegas       Nevada          United States  2020     36.2333  -115.2654  google     Las Vegas, Nevada, United States                1
               Los Angeles          us-west2                 3      Los Angeles     California      United States  2018     34.1141  -118.4068  google     Los Angeles, California, United States          1
               Montreal             northamerica-northeast1  3      Montreal        Quebec          Canada         2018     45.5089  -73.5617   google     Montreal, Quebec, Canada                        1
               North Central US     northcentralus           1      Chicago         Illinois        United States  2009     41.8375  -87.6866   microsoft  Chicago, Illinois, United States                1
               Northern Virginia    us-east4                 3      Ashburn         Virginia        United States  2017     39.0277  -77.4714   google     Ashburn, Virginia, United States                1
               Oregon               us-west1                 3      The Dalles      Oregon          United States  2013     45.6053  -121.1818  google     The Dalles, Oregon, United States               1
               Salt Lake City       us-west3                 3      Salt Lake City  Utah            United States  2020     40.7776  -111.9311  google     Salt Lake City, Utah, United States             1
               South Carolina       us-east1                 3      Moncks Corner   South Carolina  United States  2015     33.1730  -80.0107   google     Moncks Corner, South Carolina, United States    1
               South Central US     southcentralus           3      San Antonio     Texas           United States  2008     29.4632  -98.5238   microsoft  San Antonio, Texas, United States               1
               Toronto              northamerica-northeast2  3      Toronto         Ontario         Canada         2021     43.7417  -79.3733   google     Toronto, Ontario, Canada                        1
               US                   us-east-1                2      Washington      D.C.            United States  2015     38.9047  -77.0163   alibaba    Washington, D.C., United States                 1
                                    us-west-1                2      San Francisco   California      United States  2014     37.7558  -122.4449  alibaba    San Francisco, California, United States        1
               US DoD Central       usdodcentral             1      Des Moines      Iowa            United States  2017     41.5725  -93.6105   microsoft  Des Moines, Iowa, United States                 1
               US DoD East          usdodeast                1      Richmond        Virginia        United States  2017     37.5295  -77.4756   microsoft  Richmond, Virginia, United States               1
               US DoD East          us-gov-ashburn-1         1      Ashburn         Virginia        United States  2019     39.0277  -77.4714   oracle     Ashburn, Virginia, United States                1
               US DoD North         us-gov-chicago-1         1      Chicago         Illinois        United States  2020     41.8375  -87.6866   oracle     Chicago, Illinois, United States                1
               US DoD West          us-gov-phoenix-1         1      Phoenix         Arizona         United States  2019     33.5722  -112.0892  oracle     Phoenix, Arizona, United States                 1
               US East              us-ashburn-1             3      Ashburn         Virginia        United States  2017     39.0277  -77.4714   oracle     Ashburn, Virginia, United States                1
                                    us-east-1                6      Multiple        Virginia        United States  2006     37.9268  -78.0249   amazon     Multiple, Virginia, United States               1
                                    us-east-2                3      Columbus        Ohio            United States  2016     39.9862  -82.9855   amazon     Columbus, Ohio, United States                   1
               US Gov Arizona       usgovarizona             1      Phoenix         Arizona         United States  2017     33.5722  -112.0892  microsoft  Phoenix, Arizona, United States                 1
               US Gov East          us-langley-1             1      Ashburn         Virginia        United States  2018     39.0277  -77.4714   oracle     Ashburn, Virginia, United States                1
               US Gov Texas         usgovtexas               1      Austin          Texas           United States  2017     30.3005  -97.7522   microsoft  Austin, Texas, United States                    1
               US Gov Virginia      usgovvirginia            3      Washington      D.C.            United States  2014     38.9047  -77.0163   microsoft  Washington, D.C., United States                 1
               US Gov West          us-luke-1                1      Phoenix         Arizona         United States  2018     33.5722  -112.0892  oracle     Phoenix, Arizona, United States                 1
               US Midwest           us-chicago-1             3      Chicago         Illinois        United States  2022     41.8375  -87.6866   oracle     Chicago, Illinois, United States                1
               US Sec East          usseceast                1      Richmond        Virginia        United States  2020     37.5295  -77.4756   microsoft  Richmond, Virginia, United States               1
               US Sec West          ussecwest                1      San Francisco   California      United States  2020     37.7558  -122.4449  microsoft  San Francisco, California, United States        1
               US Sec West Central  ussecwestcentral         1      Des Moines      Iowa            United States  Future   41.5725  -93.6105   microsoft  Des Moines, Iowa, United States                 1
               US West              us-phoenix-1             3      Phoenix         Arizona         United States  2016     33.5722  -112.0892  oracle     Phoenix, Arizona, United States                 1
                                    us-sanjose-1             1      San Jose        California      United States  2020     37.3012  -121.8480  oracle     San Jose, California, United States             1
                                    us-west-1                3      San Francisco   California      United States  2009     37.7558  -122.4449  amazon     San Francisco, California, United States        1
                                    us-west-2                4      Eastern         Oregon          United States  2011     44.4384  -118.8918  amazon     Eastern, Oregon, United States                  1
               West Central US      westcentralus            1      Cheyenne        Wyoming         United States  2016     41.1350  -104.7902  microsoft  Cheyenne, Wyoming, United States                1
               West US              westus                   1      San Francisco   California      United States  2012     37.7558  -122.4449  microsoft  San Francisco, California, United States        1
               West US 2            westus2                  3      Moses Lake      Washington      United States  2007     47.1279  -119.2759  microsoft  Moses Lake, Washington, United States           1
               West US 3            westus3                  3      Phoenix         Arizona         United States  2021     33.5722  -112.0892  microsoft  Phoenix, Arizona, United States                 1
South America  Brazil East          sa-saopaulo-1            1      Sao Paulo       Brazil          Brazil         2019    -23.5500  -46.6333   oracle     Sao Paulo, Brazil, Brazil                       1
               Brazil Southeast     sa-vinhedo-1             1      Vinhedo         Brazil          Brazil         2021    -23.0300  -46.9750   oracle     Vinhedo, Brazil, Brazil                         1
Name: count, dtype: int64